import lexis from "./oxlint.js";

export default {
  ...lexis,
  overrides: [
    ...(lexis.overrides ?? []),
    {
      files: ["**/*.{jsx,tsx}"],
      rules: {
        "react/exhaustive-deps": "error",
        "react/forbid-dom-props": "error",
        "react/forward-ref-uses-ref": "error",
        "react/hook-use-state": "error",
        "react/iframe-missing-sandbox": "error",
        "react/jsx-boolean-value": ["error", "always"],
        "react/jsx-fragments": ["error", "syntax"],
        "react/jsx-key": "error",
        "react/jsx-no-comment-textnodes": "error",
        "react/jsx-no-constructed-context-values": "error",
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-script-url": "error",
        "react/jsx-no-target-blank": "error",
        "react/jsx-no-undef": "error",
        "react/jsx-pascal-case": "error",
        "react/jsx-props-no-spread-multi": "error",
        "react/jsx-props-no-spreading": "error",
        "react/no-array-index-key": "error",
        "react/no-children-prop": "error",
        "react/no-clone-element": "error",
        "react/no-danger-with-children": "error",
        "react/no-find-dom-node": "error",
        "react/no-multi-comp": "error",
        "react/no-object-type-as-default-prop": "error",
        "react/no-react-children": "error",
        "react/no-render-return-value": "error",
        "react/no-this-in-sfc": "error",
        "react/no-unescaped-entities": "error",
        "react/no-unknown-property": "error",
        "react/no-unsafe": "error",
        "react/no-unstable-nested-components": "error",
        "react/only-export-components": "error",
        "react/prefer-function-component": "error",
        "react/rules-of-hooks": "error",
        "react/self-closing-comp": "error",
        "react/style-prop-object": "error",
        "react/void-dom-elements-no-children": "error",
      },
    },
  ],
  plugins: [...new Set([...(lexis.plugins ?? []), "react"])],
};
