sonar.projectKey=JulianElda_arche
sonar.organization=julianelda
sonar.projectName=arche

sonar.sources=packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist-ssr/**,**/build/**,**/.svelte-kit/**,**/coverage/**,**/storybook-static/**,**/*.stories.*,packages/domos/src/routes/**,packages/scratchpad/src/**

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.svelte.test.ts,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=packages/domos/coverage/lcov.info,packages/scratchpad/coverage/lcov.info
sonar.coverage.inclusions=packages/domos/src/lib/**,packages/scratchpad/lib/**

sonar.sourceEncoding=UTF-8
